### ISSUE TITLE
Failed to compile with 1 error 

### ISSUE THREAD

**Issue by Glorious-TaehanL** [O-Z-Z-Y/lesson-app-frontend#1]
error  in ./src/store/store.js

Module not found: Error: [CaseSensitivePathsPlugin] `/Users/tedlee/Desktop/frontend/lesson-app-frontend/src/store/nav.js` does not match the corresponding path on disk `Nav.js`.

ERROR in ./src/store/store.js 2:0-24
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/tedlee/Desktop/frontend/lesson-app-frontend/src/store/nav.js` does not match the corresponding path on disk `Nav.js`.
 @ ./src/main.js 3:0-34 15:8-13

webpack compiled with 1 error

**Comment by O-Z-Z-Y** [comment]
fixed the issue. replace Nav.js to nav.js

Error detecting case modification of filenames in git

**Comment by Glorious-TaehanL** [comment]
Checked
